install: make no-gui
language: c
compiler: gcc
before_install:
    # libsdl2-dev, libsdl2-image-dev
    - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq build-essential libsdl2-dev libsdl2-image-dev
script:
    - make
    - make test
