before_install:
    - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe"
    - sudo apt-get update -qq
    - sudo apt-get install -y libsdl2-{dev,image-dev}
install: make
language: c
compiler: gcc
script:
    - make test
